### ISSUE TITLE
New dropbox link format causing issues

### ISSUE THREAD

**Issue by Hansel888** [radio1988/OneStopRNAseq#10]
Dropbox is now adding rlkeys to the end of all of their links (for more details see this link: https://www.dropboxforum.com/t5/Create-upload-and-share/Shared-Link-quot-scl-quot-to-quot-s-quot/td-p/689070)

When I paste links to dropbox files in the new format into OneStopRNAseq I get an error message indicating the file url must end with '.gz' .  Is there a way around this issue?

**Comment by radio1988** [comment]
Hello Hansel888, this is an update in Dropbox link formatting. Kai has fixed this issue. Let us know if it still does not work.
