### ISSUE TITLE
Request to use OneStopRNAseq

### ISSUE THREAD

**Issue by ghost** [radio1988/OneStopRNAseq#12]
Hello,

Hope you are doing well.

I am a postdoc at Virginia Commonwealth University, Richmond, VA.

I would like to use OneStopRNAseq but was unable to create an account as I do not have an umass email.

Can you please help me with that.

Thank you,
Anirban

**Comment by hukai916** [comment]
Hi @aniparX ,

Do you mind sharing your institutes email's suffix so that we can add it to our whitelist?

Best,

--Kai
