### ISSUE TITLE
Adapter trimming

### ISSUE THREAD

**Issue by ryland-mortlock** [radio1988/OneStopRNAseq#13]
Hi, thanks for developing this wonderful tool.
I notice that adapter trimming is performed in the pipeline, as evidenced by the FastQC files of raw fastq files versus trimmed fastq files. However, there is no documentation of this on the About page (https://mccb.umassmed.edu/OneStopRNAseq/about.php), user manual, or "Template of the Method Section".
Is the adapter trimming performed using cutadapt?
Thanks!

**Comment by radio1988** [comment]
Hello Ryland,

You're very welcome!

The trimming was done by trimmomatic.

For PE reads, "v1.23.3/bio/trimmomatic/pe" was used
For SE reads, "v1.23.3/bio/trimmomatic/se" was used.

We will update the documentations.

Best,
Rui

**Comment by ryland-mortlock** [comment]
Thanks so much!

**Comment by radio1988** [comment]
You're very welcome!
