### ISSUE TITLE
Processing Time

### ISSUE THREAD

**Issue by ADEEL2018** [radio1988/OneStopRNAseq#14]
Hello, I submitted my FASTQ files for analysis on April 21, 2024 to OneStopRNAseq web server. I am interested in knowing the typical turnaround time for receiving outputs such as differential gene expression (DGE) and gene set enrichment analysis (GSEA) results. I understand that the processing time may vary depending on the submitted jobs, but since I require these outputs for my revision, I would appreciate receiving them as soon as possible. Thank you for your assistance. 

Best regards!

**Comment by radio1988** [comment]
Hello, Thanks for bringing the issue up. We are looking at it now

**Comment by radio1988** [comment]
The problem has been addressed. The old filed jobs are being restacked into a queue. Your job will finish after it's fed into the queue. Let us know when it clears up.
