### ISSUE TITLE
module: command not found

### ISSUE THREAD

**Issue by smruti241** [radio1988/OneStopRNAseq#2]
I have gone through the installation process of onestopRNAseq. I am facing error while loading this module:
module load singularity/singularity-current
It is giving me error: module: command not found
Please tell me how to install this module in conda environment. Is there any link to install or any other way? Please let me know. Thank you.

**Comment by radio1988** [comment]
Hello smruti241, 

Currently, OneStopRNAseq (OSR) github page is for the maintenance and transparency for the OSR website (https://mccb.umassmed.edu/OneStopRNAseq/index.php). I encourage you to use our website for your RNASeq data analysis.

Currently, installing OSR in your environment would require quite some work of installing the pre-requisites. However, we are working on making OSR Snakemake workflow more portable by removing the singularity component and keeping everything in conda env. If you're more interested in downloading, installing, and using the workflow in your local computer, I will inform you when it's ready in few weeks. I will post the update in this thread.

Thanks for being interested.

Ray

**Comment by smruti241** [comment]
Okay Thank you for clarifying my issue.

**Comment by smruti241** [comment]
Hello,
I want to know actually what's the status of this tool? Can I use this for analysis or still upgradation is needed? Please let me know once.

**Comment by radio1988** [comment]
Hello smruti, the workflow is ready for use for Linux systems now. I have tested installation in Ubuntu18 and CentOS7, both worked. You can follow the installation  instructions from https://github.com/radio1988/OneStopRNAseq/blob/master/snakemake/README.md 

Basically all packages can be installed by creating a conda environment called 'osr', to keep installation relatively simple. If you run into any problems, please let me know.

Ray

**Comment by smruti241** [comment]
Thank you so much for your kind response. I will try and get back to you if
any problems occur.


Regards,
Smruti

**Comment by radio1988** [comment]
My pleasure!
