### ISSUE TITLE
Can't load results

### ISSUE THREAD

**Issue by ajg449** [radio1988/OneStopRNAseq#4]
My job completed successfully, but I am unable to load the DGE summary or download the output files. Attempting to access them causes the site to hang. Just wanted to check if this issue was on my end.

Thanks for providing this platform!

**Comment by radio1988** [comment]
what is your username and what is the analysis name? thanks!

**Comment by ajg449** [comment]
username: ajguilatco
GSE118900_DTE_test_11.59.19-03.27.2022

**Comment by hukai916** [comment]
Hi ajg449 and Rui, 
This is likely a mounting issue, I have remounted and should have fixed it. Let me know if not.

--Kai

**Comment by ajg449** [comment]
Re-mounting fixed the issue. Thank you!
