### ISSUE TITLE
website can't be reached

### ISSUE THREAD

**Issue by lihong1101** [radio1988/OneStopRNAseq#7]
Hi Rui,

I used the OneStopRNAseq website as a online RNA-seq analysis tool before, it's very nice and good for the beginner, but recently I found the website can't be opened, it said"This site can't be reached". Do you have any ideas about this?

**Comment by radio1988** [comment]
Dear user,

We are sorry to announce that our website is currently under hacker's attack, and we are working with IT to solve this problem. However, it is hard to predict when this issue will be resolved. We'll keep you updated from here.

Best,
Rui

**Comment by radio1988** [comment]
Hello Lihong,

The website is back online. If you have any further questions, just let us know.
https://mccb.umassmed.edu/OneStopRNAseq/ 

Rui

**Comment by lihong1101** [comment]
Great, thanks for let me know.

Best,
Lihong

发自我的iPhone

在 2023年2月2日，04:47，radio1988 ***@***.***> 写道：

﻿

Closed #7<https://github.com/radio1988/OneStopRNAseq/issues/7> as completed.
