### ISSUE TITLE
GSEA result Not Found

### ISSUE THREAD

**Issue by fjgallego** [radio1988/OneStopRNAseq#8]
Hello:
The result of GSEA analysis with the example data can not be accessed: 

"Not Found
The requested URL was not found on this server."

Thanks!

**Comment by radio1988** [comment]
Hello, 

Sorry about the inconvenience, can you be more specific about your question:
1.  Did you start from a RNK file, or from fastq file?
2.  Can you share the url of the results?

Thanks!

**Comment by radio1988** [comment]
I just tested the example starting from a RNK file, the results seems fine to me

**Comment by radio1988** [comment]
We did find a glitch in the udpate we are performing right now. Now it has been fixed, in my test, all GSEA results are good with the example file, start from FASTQ
