### ISSUE TITLE
Error : DATA NOT UPLOADED!

### ISSUE THREAD

**Issue by themostpurple** [radio1988/OneStopRNAseq#9]
Hi,
I am trying to do a DGE analysis from a count file. I attached said count file, which I attempted to put in the clean count format. As far as I can tell it is identical to the clean count example provided here: https://mccb.umassmed.edu/OneStopRNAseq/examples_files/file_formats/

However, it keeps on giving the following error:

error
![Screenshot 2023-05-03 132448](https://user-images.githubusercontent.com/132493932/236009475-1987a6f2-7f33-470c-91b6-b6515c8f8375.png)

said count file
[iWAT_count.mm10.xlsx](https://github.com/radio1988/OneStopRNAseq/files/11389717/iWAT_count.mm10.xlsx)

any help would be greatly appreciated. thanks!

**Comment by hukai916** [comment]
Hi @themostpurple , this was due to the file size limit on the site. I have patched it to allow files up to 100M to be uploaded. You can try again (don't forget to refresh the website) and let us know if it does not work. Thanks!

**Comment by themostpurple** [comment]
Thanks! will try again

**Comment by radio1988** [comment]
Hello @themostpurple , 

The issues related to COUNT table upload should have been fully resolved. (We found another format issue yesterday)

Can you give it another try?

Thanks!
Rui

**Comment by radio1988** [comment]
Since Kai has solved this issue. I'm closing it
